name: pandemic
channels:
  - defaults
dependencies:
  - pip
  - python
  - sqlalchemy
  - pip:
    - click
    - flask
    - flask-bootstrap
    - flask-nav
    - flask-sqlalchemy
    - flask-wtf
    - wtforms
